name: custom_fragment_shader
description: A project to introduce Custom Fragment Shader in slide format.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.13.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^11.1.2
  collection: ^1.17.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8
      path: plugins/window_size
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  scroll_to_index: ^3.0.1
  flutter_shaders: ^0.1.2
  flutter_animate: ^4.2.0+1
  gap: ^3.0.1
  qr_flutter: ^4.1.0
  highlight: ^0.7.0
  widget_arrows: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/agenda01/
    - assets/agenda02/
    - assets/agenda04/
    - google_fonts/Poppins/
  shaders:
    - shaders/title_background.frag
    - shaders/orange.frag
    - shaders/gradient.frag
    - shaders/pixelation.frag
    - shaders/hologram_effect.frag
    - shaders/gloss_effect.frag
    - shaders/transition.frag

flutter_gen:
  integrations:
    flutter_svg: true
